# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Cypress test
on:
  push: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch to checkout and run test'
        required: false
        default: master

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Run cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
         
